DEFAULT_SEARCH_SCORE = 1.
DEFAULT_NUMBER_OF_PAGE_SEARCH_RESULTS = 100
DEFAULT_NUMBER_OF_TEXT_SEARCH_RESULTS = 5
ENWIKI_URL = "https://en.wikipedia.org/w/api.php"
DEFAULT_EMBEDDINGS_MODEL = 'all-MiniLM-L6-v2'
