DEFAULT_SEARCH_SCORE = 1.
DEFAULT_NUMBER_OF_PAGE_SEARCH_RESULTS = 10
DEFAULT_NUMBER_OF_TEXT_SEARCH_RESULTS = 10
ENWIKI_URL = "https://en.wikipedia.org/w/api.php"
DEFAULT_EMBEDDINGS_MODEL = 'all-MiniLM-L6-v2'
DEFAULT_QNA_MODEL = "deepset/roberta-base-squad2"
QA_MIN_SCORE = 0.1
